import { randomUUID } from "node:crypto";
import type { Clock } from "../../../platform/clock.js";
import { CapabilityError } from "../../capability/contracts/index.js";
import type { RoleGrantRepository } from "../../authorization/contracts/index.js";
import { Organization } from "../domain/organization.entity.js";
import { OrganizationSlugTakenError } from "../domain/organization.repository.js";
import type { OrganizationRepository } from "../domain/organization.repository.js";
import { Membership } from "../domain/membership.entity.js";
import type { MembershipRepository } from "../domain/membership.repository.js";
import type { OrganizationDto } from "../contracts/tenant.contract.js";

export interface CreateOrganizationCommand {
  /**
   * Generated by the caller *before* the transaction opens, because it is
   * also the new tenant's id and therefore has to be in the RLS context that
   * the transaction is opened with. See OrganizationController.
   */
  organizationId: string;
  creatorUserId: string;
  name: string;
  slug: string;
}

/** The role the organization's creator is granted. Platform-defined; seeded by the permission-catalog migration. */
const OWNER_ROLE_KEY = "owner";

/**
 * 08_PHASE_1_BRIEF.md §2 step 7 for `organization.create`: one use case, one
 * file, no audit write of its own (that is step 8, owned by the composition
 * root, per ADR-034 item 6).
 *
 * Creating the organization also makes its creator the first ACTIVE member
 * and grants them the `owner` role, in the same transaction. That is not
 * scope creep: every subsequent capability authorizes through
 * `membership_roles` (step 6), so an organization created without it would
 * be permanently unusable and the remaining Phase 1 slices
 * (`membership.invite`, `organization.switch`) would have no reachable
 * starting state. Recorded in DECISION_LOG.md.
 */
export class CreateOrganizationService {
  constructor(
    private readonly organizations: OrganizationRepository,
    private readonly memberships: MembershipRepository,
    private readonly roleGrants: RoleGrantRepository,
    private readonly clock: Clock,
  ) {}

  async execute(command: CreateOrganizationCommand): Promise<OrganizationDto> {
    const createdAt = this.clock.now();
    const organization = new Organization(
      command.organizationId,
      command.organizationId,
      command.name,
      command.slug,
      "ACTIVE",
      createdAt,
    );

    try {
      await this.organizations.create(organization);
    } catch (err) {
      if (err instanceof OrganizationSlugTakenError) {
        throw new CapabilityError("CONFLICT", "That organization slug is already taken.", { slug: command.slug });
      }
      throw err;
    }

    const membership = new Membership(randomUUID(), organization.id, command.creatorUserId, "ACTIVE", createdAt);
    await this.memberships.create(membership);
    await this.roleGrants.grantRoleByKey({
      id: randomUUID(),
      tenantId: organization.id,
      membershipId: membership.id,
      roleKey: OWNER_ROLE_KEY,
      createdAt,
    });

    return {
      id: organization.id,
      name: organization.name,
      slug: organization.slug,
      status: organization.status,
      createdAt: organization.createdAt.toISOString(),
    };
  }
}
