import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { Client } from "pg";
import { checkImports } from "./rules/imports.js";
import { checkSingletons } from "./rules/singleton.js";
import { checkSchema } from "./rules/schema.js";
import { checkSecrets } from "./rules/secrets.js";
import { checkSchemaLive } from "./rules/schema-live.js";
import { checkDbAccess } from "./rules/db-access.js";
import { checkErrorCodeContract } from "./rules/error-codes.js";
import { loadExceptions, applyExceptions } from "./lib/exceptions.js";
import { loadMigrateDbConfig } from "../../platform/config.js";
import { discoverModuleMigrations } from "../../platform/db/discover-migrations.js";
import { migrate } from "../../platform/db/migrate.js";
import { describeDbError } from "../../platform/db/describe-error.js";
import type { Violation } from "./lib/types.js";

const ROOT = process.cwd();
const EXCEPTIONS_PATH = join(ROOT, "exceptions.json");
const REPORT_PATH = join(ROOT, "conformance-exceptions-report.md");

async function run() {
  const violations: Violation[] = [
    ...checkImports(ROOT),
    ...checkSingletons(ROOT),
    ...checkSchema(ROOT),
    ...checkSecrets(ROOT),
    ...checkDbAccess(ROOT),
    ...checkErrorCodeContract(ROOT),
    ...(await checkSchemaLiveAgainstRealTree()),
  ];

  const exceptions = loadExceptions(EXCEPTIONS_PATH);
  const { suppressed, remaining, invalidEntries } = applyExceptions(violations, exceptions);

  writeReport(suppressed);

  if (invalidEntries.length > 0) {
    const noun = invalidEntries.length === 1 ? "entry" : "entries";
    const verb = invalidEntries.length === 1 ? "has" : "have";
    console.error(`\n${invalidEntries.length} ${noun} in exceptions.json ${verb} no valid ADR reference (expected "ADR-###"):`);
    for (const e of invalidEntries) {
      console.error(`  - ${e.rule} ${e.file}: adr="${e.adr ?? ""}"`);
    }
  }

  if (remaining.length === 0 && invalidEntries.length === 0) {
    console.log(`Conformance harness: PASS (0 violations, ${suppressed.length} justified exception(s))`);
    process.exit(0);
  }

  console.error(`\nConformance harness: FAIL (${remaining.length} violation(s))\n`);
  for (const v of remaining) {
    console.error(`[${v.rule}] ${v.file}`);
    console.error(`  ${v.message}`);
    console.error(`  fix: ${v.fix}\n`);
  }
  process.exit(1);
}

/**
 * Live-DB companion to checkSchema() (static SQL parsing): applies the real
 * per-module migrations tree (modules/<module>/migrations) to the configured
 * database and introspects it. Best-effort — if no database is reachable this
 * is logged and skipped rather
 * than failing CI, because Phase 0's real modules/ tree has zero migrations
 * and not every environment running `npm run conformance` has Postgres up
 * (the self-test suite's live-DB spec is what makes the mechanism a hard
 * requirement — see tools/conformance/harness.selftest.live-db.spec.ts).
 *
 * Uses the migrate role (nexora_migrate), not the app role: it needs DDL
 * rights to apply migrations, and this check is structural (does RLS/FORCE/
 * tenant_id exist in the catalogs), not a proof of row-level isolation
 * behavior — that distinction matters for which role is safe to use here.
 * See DECISION_LOG.md "RLS: FORCE ROW LEVEL SECURITY or a non-owner app role".
 */
async function checkSchemaLiveAgainstRealTree(): Promise<Violation[]> {
  const config = loadMigrateDbConfig();
  const client = new Client({ connectionString: config.connectionString });
  try {
    await client.connect();
  } catch (err) {
    console.log(`(live-DB schema check skipped: could not reach ${config.connectionString} — ${describeDbError(err)})`);
    return [];
  }

  try {
    const files = discoverModuleMigrations(join(ROOT, "modules"));
    await migrate(client, "public", files);
    return await checkSchemaLive(client, "public");
  } finally {
    await client.end();
  }
}

function writeReport(suppressed: Array<Violation & { reason: string; adr: string }>) {
  const lines = [
    "# Conformance Exceptions Report",
    "",
    "Generated by `npm run conformance`. Do not hand-edit — edit `exceptions.json` instead.",
    "",
  ];
  if (suppressed.length === 0) {
    lines.push("No exceptions on record. The conformance harness is clean.");
  } else {
    lines.push("| Rule | File | ADR | Reason |", "|---|---|---|---|");
    for (const s of suppressed) {
      lines.push(`| ${s.rule} | ${s.file} | ${s.adr} | ${s.reason} |`);
    }
  }
  writeFileSync(REPORT_PATH, lines.join("\n") + "\n", "utf8");
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
