import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { checkImports } from "./rules/imports.js";
import { checkSingletons } from "./rules/singleton.js";
import { checkSchema } from "./rules/schema.js";
import { checkSecrets } from "./rules/secrets.js";
import { loadExceptions, applyExceptions } from "./lib/exceptions.js";
import type { Violation } from "./lib/types.js";

const ROOT = process.cwd();
const EXCEPTIONS_PATH = join(ROOT, "exceptions.json");
const REPORT_PATH = join(ROOT, "conformance-exceptions-report.md");

function run() {
  const violations: Violation[] = [
    ...checkImports(ROOT),
    ...checkSingletons(ROOT),
    ...checkSchema(ROOT),
    ...checkSecrets(ROOT),
  ];

  const exceptions = loadExceptions(EXCEPTIONS_PATH);
  const { suppressed, remaining, invalidEntries } = applyExceptions(violations, exceptions);

  writeReport(suppressed);

  if (invalidEntries.length > 0) {
    const noun = invalidEntries.length === 1 ? "entry" : "entries";
    const verb = invalidEntries.length === 1 ? "has" : "have";
    console.error(`\n${invalidEntries.length} ${noun} in exceptions.json ${verb} no valid ADR reference (expected "ADR-###"):`);
    for (const e of invalidEntries) {
      console.error(`  - ${e.rule} ${e.file}: adr="${e.adr ?? ""}"`);
    }
  }

  if (remaining.length === 0 && invalidEntries.length === 0) {
    console.log(`Conformance harness: PASS (0 violations, ${suppressed.length} justified exception(s))`);
    process.exit(0);
  }

  console.error(`\nConformance harness: FAIL (${remaining.length} violation(s))\n`);
  for (const v of remaining) {
    console.error(`[${v.rule}] ${v.file}`);
    console.error(`  ${v.message}`);
    console.error(`  fix: ${v.fix}\n`);
  }
  process.exit(1);
}

function writeReport(suppressed: Array<Violation & { reason: string; adr: string }>) {
  const lines = [
    "# Conformance Exceptions Report",
    "",
    "Generated by `npm run conformance`. Do not hand-edit — edit `exceptions.json` instead.",
    "",
  ];
  if (suppressed.length === 0) {
    lines.push("No exceptions on record. The conformance harness is clean.");
  } else {
    lines.push("| Rule | File | ADR | Reason |", "|---|---|---|---|");
    for (const s of suppressed) {
      lines.push(`| ${s.rule} | ${s.file} | ${s.adr} | ${s.reason} |`);
    }
  }
  writeFileSync(REPORT_PATH, lines.join("\n") + "\n", "utf8");
}

run();
