import { sql } from "kysely";
import type { Kysely, Transaction } from "kysely";
import type { Database } from "../../../platform/db/kysely.js";
import { isUniqueViolation } from "../../../platform/db/constraint-violation.js";
import { Subscription, SubscriptionPeriod } from "../domain/subscription.entity.js";
import type { PeriodStatus } from "../domain/subscription.entity.js";
import { TrialAlreadyUsedError } from "../domain/subscription.repository.js";
import type { CreateSubscriptionCommand, SubscriptionRepository } from "../domain/subscription.repository.js";
import type { SubscriptionStatus } from "../domain/subscription-status.js";
import "./subscription.tables.js";

/** The partial unique index from the creating migration (ADR-052 item 3). */
const ONE_TRIAL_PER_TENANT = "subscriptions_one_trial_per_tenant";

const SUBSCRIPTION_COLUMNS = [
  "id",
  "tenant_id",
  "plan_version_id",
  "price_version_id",
  "status",
  "auto_renew",
  "current_period_id",
  "trial_end",
  "canceled_at",
  "reactivation_deadline",
  "version",
] as const;

export class SubscriptionRepositoryPg implements SubscriptionRepository {
  constructor(private readonly conn: Kysely<Database> | Transaction<Database>) {}

  /**
   * Three writes, one transaction — the caller's, never one opened here.
   * `platform/db/tenant-context.ts` is the only place a transaction is opened
   * in this codebase (ADR-030's singleton rule), and the capability has already
   * opened it before this repository is constructed.
   *
   * The order is forced by the mutual reference: the period names the
   * subscription, so the subscription must exist first; the subscription then
   * names the period back. `id`s are supplied by the caller rather than
   * generated by the database, matching every other insert in this codebase.
   */
  async create(command: CreateSubscriptionCommand): Promise<void> {
    const { subscription: s, firstPeriod: p } = command;

    try {
      await this.conn
        .insertInto("subscriptions")
        .values({
          id: s.id,
          tenant_id: s.tenantId,
          plan_version_id: s.planVersionId,
          price_version_id: s.priceVersionId,
          status: s.status,
          term_length: s.termLength,
          auto_renew: s.autoRenew,
          current_period_id: null,
          trial_end: s.trialEnd?.toISOString() ?? null,
          canceled_at: s.canceledAt?.toISOString() ?? null,
          reactivation_deadline: s.reactivationDeadline?.toISOString() ?? null,
        })
        .execute();
    } catch (err) {
      if (isUniqueViolation(err, ONE_TRIAL_PER_TENANT)) {
        throw new TrialAlreadyUsedError(s.tenantId);
      }
      throw err;
    }

    await this.conn
      .insertInto("subscription_periods")
      .values({
        id: p.id,
        tenant_id: p.tenantId,
        subscription_id: p.subscriptionId,
        plan_version_id: p.planVersionId,
        price_version_id: p.priceVersionId,
        period_start: p.periodStart.toISOString(),
        period_end: p.periodEnd.toISOString(),
        grace_end: p.graceEnd?.toISOString() ?? null,
        invoice_id: p.invoiceId,
        status: p.status,
      })
      .execute();

    await this.conn.updateTable("subscriptions").set({ current_period_id: p.id }).where("id", "=", s.id).execute();
  }

  async findByTenant(tenantId: string): Promise<Subscription | null> {
    const row = await this.conn
      .selectFrom("subscriptions")
      .select([...SUBSCRIPTION_COLUMNS, sql<string>`term_length::text`.as("term_length_text")])
      .where("tenant_id", "=", tenantId)
      .orderBy("created_at", "desc")
      .executeTakeFirst();
    if (!row) return null;

    return new Subscription(
      row.id,
      row.tenant_id,
      row.plan_version_id,
      row.price_version_id,
      row.status as SubscriptionStatus,
      row.term_length_text,
      row.auto_renew,
      row.current_period_id,
      row.trial_end,
      row.canceled_at,
      row.reactivation_deadline,
      row.version,
    );
  }

  async existsForTenant(tenantId: string): Promise<boolean> {
    const row = await this.conn
      .selectFrom("subscriptions")
      .select("id")
      .where("tenant_id", "=", tenantId)
      .executeTakeFirst();
    return row !== undefined;
  }

  async findPeriodById(periodId: string): Promise<SubscriptionPeriod | null> {
    const row = await this.conn
      .selectFrom("subscription_periods")
      .selectAll()
      .where("id", "=", periodId)
      .executeTakeFirst();
    if (!row) return null;

    return new SubscriptionPeriod(
      row.id,
      row.tenant_id,
      row.subscription_id,
      row.plan_version_id,
      row.price_version_id,
      row.period_start,
      row.period_end,
      row.grace_end,
      row.invoice_id,
      row.status as PeriodStatus,
    );
  }
}
